<a href="https://colab.research.google.com/github/madhu9sudhana/Python_Examples/blob/master/Matrix_Operations_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Matrix Operations 
### Functions written in Python without directly using Numpy


1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Matrix Transpose
5. Determinant of Matrix
6. Matrix Inverse

In [0]:
import pandas as pd
import numpy as np
import os

def Nmul(x,y):
  if x.shape[1] == y.shape[0]:
    z = []
    for i in range(0,len(x)):
      temp=[]
      for j in range(0,len(y[0])):
          s = 0
          for k in range(0,len(x[0])):
              s += x[i][k]*y[k][j]
          temp.append(s)
      z.append(temp)
    z = np.asarray(z)
    return z
  else:
    return print("Matrix muliplication is not possible")
  
def Nadd(x,y):
  if x.shape[1] == y.shape[0]:
    z = []
    for i in range(0,len(x)):
      temp=[]
      for j in range(0,len(y[0])):
          s = 0
          for k in range(0,len(x[0])):
            s = x[i][j]+y[i][j]
          temp.append(s)
      z.append(temp)
    z = np.asarray(z)
    return z
  else:
    return print("Matrix addition is not possible")
  
def Nsub(x,y):
  if x.shape[1] == y.shape[0]:
      z = []
      for i in range(0,len(x)):
        temp=[]
        for j in range(0,len(y[0])):
            s = 0
            for k in range(0,len(x[0])):
                s = x[i][j]-y[i][j]
            temp.append(s)
        z.append(temp)
      z = np.asarray(z)
      return z
  else:
      return print("Matrix Subtraction is not possible")
    
def Ntran(x):
  rez = [[x[j][i] for j in range(len(x))] for i in range(len(x[0]))] 
  rez = np.asarray(rez)
  return(rez)

def transposeMatrix(m):
    return map(list,zip(*m))

def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

def NMatrixDeternminant(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*NMatrixDeternminant(getMatrixMinor(m,0,c))
    return determinant

def NMatrixInverse(m):
    determinant = NMatrixDeternminant(m)
    #special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

    #find matrix of cofactors
    cofactors = []
    for r in range(len(m)):
        cofactorRow = []
        for c in range(len(m)):
            minor = getMatrixMinor(m,r,c)
            cofactorRow.append(((-1)**(r+c)) * NMatrixDeternminant(minor))
        cofactors.append(cofactorRow)
    cofactors = transposeMatrix(cofactors)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant
    return cofactors

### Define some matrices as examples

In [0]:
x = np.array( ((2,3), (4, 5)) )
y = np.array( ((1,2), (5, -1)) )
w = np.array( ((1,2,5), (5, -1,6), (3, 5,3)) )

print(x, '\n\n', y, '\n\n', w)

[[2 3]
 [4 5]] 

 [[ 1  2]
 [ 5 -1]] 

 [[ 1  2  5]
 [ 5 -1  6]
 [ 3  5  3]]


## Matrix Operations : Addition

In [0]:
print(Nadd(x, y))
print(x+y)

[[3 5]
 [9 4]]
[[3 5]
 [9 4]]


## Matrix Operations : Subtraction

In [0]:
Nsub(x,y)

array([[ 1,  1],
       [-1,  6]])

## Matrix Multiplication

In [0]:
Nmul(x, y)

array([[17,  1],
       [29,  3]])

## Matrix Transpose


In [0]:
Ntran(x)

array([[2, 4],
       [3, 5]])

##Determinant of Matrix

In [0]:
NMatrixDeternminant(x)

-2

## Matrix Inverse

In [0]:
np.asarray(NMatrixInverse(x))

array([[-2.5,  1.5],
       [ 2. , -1. ]])