<a href="https://colab.research.google.com/github/madhu9sudhana/Python_Examples/blob/master/PCA_Try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import os

In [44]:
x = np.array( ((2,3), (3, 5)) )
print(x)

[[2 3]
 [3 5]]


In [45]:
y = np.array( ((1,2), (5, -1)) )
print(y)

[[ 1  2]
 [ 5 -1]]


In [58]:
w = np.array( ((1,2,5), (5, -1,6), (3, 5,3)) )
print(w)

[[ 1  2  5]
 [ 5 -1  6]
 [ 3  5  3]]


## Matrix Operations : Addition

In [46]:
x + y


array([[3, 5],
       [8, 4]])

## Matrix Operations : Subtraction

In [47]:
x - y

array([[ 1,  1],
       [-2,  6]])

##Matrix Operation :  Scalar Multiplication

In [72]:
2 * y

array([[ 2,  4],
       [10, -2]])

## Matrix Operations : Dot Products - Numpy

In [65]:
type(np.dot(x,y))

numpy.ndarray

##Matrix Multiplication without Numpy

In [0]:
def Multiply(x,y):
  if x.shape[1] == y.shape[0]:
    z = []
    for i in range(0,len(x)):
      temp=[]
      for j in range(0,len(y[0])):
          s = 0
          for k in range(0,len(x[0])):
              s += x[i][k]*y[k][j]
          temp.append(s)
      z.append(temp)
    z = np.asarray(z)
    return z
  else:
    return print("Matrix muliplication is not possible")

## Example of Matrix Multiplication 

In [70]:
Multiply(x, y)

array([[17,  1],
       [28,  1]])

In [59]:
Multiply(x, w)

Matrix Muliplication not Possible


## Eigen value and Eigen vector Calculation using Numpy

In [78]:
e_vals, e_vecs = np.linalg.eig(w)
print(e_vals,"\n")
print(e_vecs)

[ 9.84997656 -2.91662208 -3.93335448] 

[[-0.49533504 -0.63893326 -0.38385664]
 [-0.58393457 -0.39661341 -0.66214471]
 [-0.64316687  0.65913739  0.64359806]]


# Importing Sample data for PCA 

In [9]:
from google.colab import files
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving PCA_Data.csv to PCA_Data.csv
User uploaded file "PCA_Data.csv" with length 259 bytes


In [11]:
df = pd.read_csv(io.StringIO(uploaded['PCA_Data.csv'].decode('utf-8')))
print(df)

  BodyShape  Calorie  Breakfast  Lunch  Dinner  Exercise
0    Skinny     1200          1      0       0         2
1    Normal     2800          1      1       1         1
2       Fat     3500          2      2       1         0
3    Skinny     1400          0      1       0         3
4       Fat     5000          2      2       2         0
5    Skinny     1300          0      0       1         2
6    Normal     3000          1      0       1         1
7       Fat     4000          2      2       2         0
8    Normal     2600          0      2       0         0
9       Fat     3000          1      2       1         1
